// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
          apiKey: "AIzaSyDTaW_q6YPyrh9lF5icJN6avcf79uLDBMc",
          authDomain: "chatify-app-368c1.firebaseapp.com",
          projectId: "chatify-app-368c1",
          storageBucket: "chatify-app-368c1.appspot.com",
          messagingSenderId: "214629633067",
          appId: "1:214629633067:web:879618fe53e752f3336e6e",
          measurementId: "G-HFT6CG52QD");
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNS-Jm1Ef_6SMt6um-bJD4COaKqpIZhc',
    appId: '1:214629633067:android:e4bd520951472d3f336e6e',
    messagingSenderId: '214629633067',
    projectId: 'chatify-app-368c1',
    storageBucket: 'chatify-app-368c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_8PsZfKxm8Ty3-MemAX6Usr4fvVcAYY',
    appId: '1:214629633067:ios:bf8119122db844e8336e6e',
    messagingSenderId: '214629633067',
    projectId: 'chatify-app-368c1',
    storageBucket: 'chatify-app-368c1.appspot.com',
    iosBundleId: 'com.example.chatifyApp',
  );
}
